<a href="https://colab.research.google.com/github/Xavier-Brooke/My-Coding-Journey/blob/main/python/2)DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

**Creating a DataFrame**

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [ ]:
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns = ["Name","Age","City","Salary"]

In [ ]:
df2 = pd.DataFrame(data_list, columns=columns) ;
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and Indexing of columns

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df[["Name", 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Creating a new Column

In [ ]:
df["Designation"] = ["Doct.", "Eng.", "Lawer", "Police"] ;

In [ ]:
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000       Doct.
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000       Lawer
3  Linda   42    London   85000      Police

Removing Columns

In [ ]:
newDf = df.drop(2, axis=0)
print(newDf) ;
print(df) ;

    Name  Age      City  Salary Designation
0   John   28  New York   65000       Doct.
1   Anna   34     Paris   70000        Eng.
3  Linda   42    London   85000      Police
    Name  Age      City  Salary Designation
0   John   28  New York   65000       Doct.
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000       Lawer
3  Linda   42    London   85000      Police

In [ ]:
index = ["1", "2", "3", "4"] ;
df = pd.DataFrame(data_list, index=index, columns=columns)

In [ ]:
df

    Name  Age      City  Salary
1   John   28  New York   65000
2   Anna   34     Paris   70000
3  Peter   29    Berlin   62000
4  Linda   42    London   85000

In [ ]:
df.drop("2", axis=0)

    Name  Age      City  Salary
1   John   28  New York   65000
3  Peter   29    Berlin   62000
4  Linda   42    London   85000

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.loc[[1,2]]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [ ]:
(df2.loc[[0,1]])[["Name", "City", "Salary"]]

   Name      City  Salary
0  John  New York   65000
1  Anna     Paris   70000

In [ ]:
df

    Name  Age      City  Salary
1   John   28  New York   65000
2   Anna   34     Paris   70000
3  Peter   29    Berlin   62000
4  Linda   42    London   85000

In [ ]:
df.iloc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 1, dtype: object

In [ ]:
df.iloc[[0, 1, 2]]

    Name  Age      City  Salary
1   John   28  New York   65000
2   Anna   34     Paris   70000
3  Peter   29    Berlin   62000

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
df2.loc[[0, 1, 2]][["Name", "City", "Salary"]]

    Name      City  Salary
0   John  New York   65000
1   Anna     Paris   70000
2  Peter    Berlin   62000

Conditional Section

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# selecting those rows in which age > 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
# selecting those rows in which age > 30 and city == "Paris"
df2[(df2["Age"] > 30) & (df2["City"] != "Paris")]

    Name  Age    City  Salary
3  Linda   42  London   85000